# This is an appspec.yml template file for use with AWS CodeDeploy.
# The lines in this template starting with the hashtag symbol are 
#   instructional comments and can be safely left in the file or 
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux or Ubuntu Server  
#   instances.
# Specify "os: windows" if this revision targets Windows Server instances.
# (You cannot specify both "os: linux" and "os: windows".)
os: linux 
# os: windows
# During the Install deployment lifecycle event (which occurs between the 
#   BeforeInstall and AfterInstall events), copy the specified files 
#   in "source" starting from the root of the revision's file bundle 
#   to "destination" on the instance.
# Specify multiple "source" and "destination" pairs if you want to copy 
#   from multiple sources or to multiple destinations.
# If you are not copying any files to the instance, then remove the
#   "files" section altogether. A blank or incomplete "files" section
#   may cause associated deployments to fail.
files:
  - source: .
    destination: /cloudpatrol
# For deployments to Amazon Linux and Ubuntu Server instances,
#   you can specify a "permissions" 
#   section here that describes special permissions to apply to the files 
#   in the "files" section as they are being copied over to 
#   the instance.
#   For more information, see the documentation.
# If you are deploying to Windows Server instances,
#   then remove the 
#   "permissions" section altogether. A blank or incomplete "permissions"
#   section may cause associated deployments to fail.
permissions:
  - object: /cloudpatrol
#    except:
    owner: root
    group: root
    mode: 644
    # acls:
    #   -
    # context:
    #   user:
    #   type:
    #   range:
    # type:
    #   -
# If you are not running any commands on the instance, then remove 
#   the "hooks" section altogether. A blank or incomplete "hooks" section
#   may cause associated deployments to fail.
hooks:
  ApplicationStop:
    - location: scripts/applicationStop.sh
      timeout: 15
      runas: root
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 15
      runas:  root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh   
      timeout: 15
      runas: root
  ValidateService:
    - location: scripts/validateService.sh   
      timeout: 15
      runas: root
