User.create(name: "admin", password: "admin", password_confirmation: "admin")
Setting.create(key: "aws_access_key_id", value: "", protected: "key")
Setting.create(key: "aws_secret_access_key", value: "", protected: "key")
Setting.create(key: "opsworks_stack_age", value: "", protected: "key")
Setting.create(key: "opsworks_layer_age", value: "", protected: "key")
Setting.create(key: "opsworks_instance_age", value: "", protected: "key")
Setting.create(key: "opsworks_app_age", value: "", protected: "key")
